dir: src

packageJson: package.json

articles:

    - Overview : doc/manual/overview.md
    - Installation : doc/manual/installation.md
    - Usage : doc/manual/usage.md
    - Example : doc/manual/example.md

